spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/hellobatch?useUnicode=true&characterEncoding=utf8
    username: maria
    password: p@ssw0rd
    driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
